version: '3'

# volumes:
  # production_postgres_data: {}
  # production_postgres_data_backups: {}
  # production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: summarizer.azurecr.io/meeting_summary_production_django:0.1.0
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 4G
        # limits:
        #   cpus: '4'
        #   memory: 8G
    # depends_on:
      # - postgres
      # - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: summarizer.azurecr.io/meeting_summary_production_nginx:0.1.0
    ports:
      - "80:80"
      - "443:443"
    domainname: acs-custom-summarizer

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/postgres/Dockerfile
  #   image: meeting_summary_production_postgres
  #   volumes:
  #     - production_postgres_data:/var/lib/postgresql/data:Z
  #     - production_postgres_data_backups:/backups:z
  #   env_file:
  #     - ./.envs/.production/.postgres

  # traefik:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/traefik/Dockerfile
  #   image: meeting_summary_production_traefik
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_traefik:/etc/traefik/acme:z
  #   ports:
  #     - "0.0.0.0:80:80"
  #     - "0.0.0.0:443:443"

  # redis:
  #   image: redis:5.0
