# Generated by Django 3.1.13 on 2021-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='captions',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
    ]
